version: '3.8'

services:
  oracle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trustless-bridge-oracle
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Example command with required arguments
    command: ["--contract-address", "0x8C7352cF35435Ebe69D6C3B636A0E65F9C5Bc6A9", "--network", "testnet", "--bitcoin-network", "testnet"]
    # Remove the volumes to ensure the container uses the built files
    # volumes:
    #   - ./src:/app/src
    #   - ./dist:/app/dist 