version: '3.8'

services:
  oracle:
    image: "ghcr.io/momannn/trustless-bridge-oracle:latest"
    platform: linux/amd64
    container_name: trustless-bridge-oracle
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    # Example command with required arguments
    command: ["--contract-address", "0xCC36DA877326b7211b6b679546D7ee9c41d23636", "--network", "testnet", "--bitcoin-network", "testnet"]
    # Remove the volumes to ensure the container uses the built files
    # volumes:
    #   - ./src:/app/src
    #   - ./dist:/app/dist 